// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface AboutSummary {
  image?: StoryblokAsset;
  headline?: Headline[];
  description?: StoryblokRichtext;
  desktop_reverse_layout?: boolean;
  mobile_reverse_layout?: boolean;
  background_color?: "" | "Default" | "Primary" | "Muted" | "Secondary";
  image_aspect_ratio?: "" | "square" | "portrait" | "landscape" | "auto";
  component: "aboutSummary";
  _uid: string;
  [k: string]: unknown;
}

export interface AuthItem {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  style?: "" | "Default" | "Ghost";
  background_color?: "" | "Primary" | "Highligh_1" | "hHghlight_2";
  text_color?: "" | "White" | "Dark";
  small?: "" | "Small" | "Medium" | "Large";
  component: "authItem";
  _uid: string;
  [k: string]: unknown;
}

export interface Buttons {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "buttons";
  _uid: string;
  [k: string]: unknown;
}

export interface Entries {
  image?: StoryblokAsset;
  headline?: string;
  description?: StoryblokRichtext;
  button?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  component: "entries";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterAbout {
  description?: string;
  socials?: Socails[];
  component: "footerAbout";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterItem {
  title?: string;
  footer_item?: InnierFooterItem[];
  component: "footerItem";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterSection {
  footer_about?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  learn?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  category?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  legal_support?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  component: "footerSection";
  _uid: string;
  [k: string]: unknown;
}

export interface GridCard {
  label?: string;
  description?: string;
  icon?: StoryblokAsset;
  icon_width?: "" | "48" | "80" | "160" | "200";
  row_span?: "" | "1" | "2";
  border?: boolean;
  image?: StoryblokAsset;
  component: "gridCard";
  _uid: string;
  [k: string]: unknown;
}

export interface HappyCustomer {
  headline?: Headline[];
  description?: StoryblokRichtext;
  background_color?: "" | "White" | "Primary" | "Muted" | "Secondary";
  reverser_mobile_layout?: boolean;
  reverse_destop_layout?: boolean;
  button?: Buttons[];
  image?: StoryblokAsset;
  image_aspect_ratio?: "" | "square" | "portrait" | "landscape" | "auto";
  fallback_description?: string;
  component: "happyCustomer";
  _uid: string;
  [k: string]: unknown;
}

export interface HeaderNav {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "headerNav";
  _uid: string;
  [k: string]: unknown;
}

export interface Headline {
  text?: string;
  highlight?: "" | "Default Highlight" | "Primary Highlight" | "Secondary Highlight" | "White Highlight";
  component: "headline";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  servicing?: string;
  headline?: Headline[];
  description?: string;
  buttons?: Buttons[];
  image?: StoryblokAsset;
  background_color?: "" | "White" | "Gradient" | "Custom";
  component: "heroSection";
  _uid: string;
  [k: string]: unknown;
}

export interface InnierFooterItem {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "innierFooterItem";
  _uid: string;
  [k: string]: unknown;
}

export interface NavBar {
  logo_title?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  header_nav?: HeaderNav[];
  auth_item?: AuthItem[];
  component: "navBar";
  _uid: string;
  [k: string]: unknown;
}

export interface OtherHeroSection {
  headline?: Headline[];
  description?: string;
  explore_service?: Buttons[];
  image?: StoryblokAsset;
  image_height?: "" | "Small" | "Medium" | "Large" | "Full";
  image_opacity?: "" | "Light" | "Dark" | "Medium" | "Default";
  component: "otherHeroSection";
  _uid: string;
  [k: string]: unknown;
}

export interface OurSevices {
  headline?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  description?: string;
  grid_card?: GridCard[];
  columns?: "" | "2" | "3" | "4";
  background_color?: "" | "White" | "Primary" | "Muted" | "Secondary";
  general_button?: Buttons[];
  no_service?: string;
  no_service_description?: string;
  component: "ourSevices";
  _uid: string;
  [k: string]: unknown;
}

export interface OurTeam {
  headline?: Headline[];
  description?: string;
  team_card?: TeamCard[];
  columns?: "" | "2" | "3" | "4";
  background_color?: "" | "White" | "Primary" | "Secondary" | "Default";
  component: "ourTeam";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface ProviderDetails {
  image?: StoryblokAsset;
  name?: string;
  service?: string;
  email?: string;
  phone_number?: string;
  get_in_touch?: Buttons[];
  component: "providerDetails";
  _uid: string;
  [k: string]: unknown;
}

export interface ProviderSection {
  headline?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  description?: string;
  search_placeholder?: string;
  providers_headline?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  provider_details?: ProviderDetails[];
  columns?: "" | "2" | "3" | "4";
  search_no_provider?: string;
  no_provider_search_item?: string;
  no_provider_yet?: string;
  no_provider_description?: string;
  component: "providerSection";
  _uid: string;
  [k: string]: unknown;
}

export interface ServiceDetails {
  title?: string;
  details?: string;
  image?: StoryblokAsset;
  image_aspect_ratio?: boolean;
  component: "serviceDetails";
  _uid: string;
  [k: string]: unknown;
}

export interface ServicesPart {
  headline?: Headline[];
  description?: StoryblokRichtext;
  image?: StoryblokAsset;
  image_aspect_ratio?: boolean;
  desktop_layout?: boolean;
  mobile_layout?: boolean;
  section_background_color?: "" | "White" | "Primary" | "Muted" | "Secondary";
  component: "servicesPart";
  _uid: string;
  [k: string]: unknown;
}

export interface ServicesSection {
  headline?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  description?: string;
  sevice?: ServicesPart[];
  component: "servicesSection";
  _uid: string;
  [k: string]: unknown;
}

export interface SiteLogo {
  logo?: StoryblokAsset;
  site_name?: Headline[];
  component: "siteLogo";
  _uid: string;
  [k: string]: unknown;
}

export interface Socails {
  icon?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "socails";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialLinks {
  platform?: string;
  url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  icon?: StoryblokAsset;
  component: "socialLinks";
  _uid: string;
  [k: string]: unknown;
}

export interface StatCard {
  prefix?: string;
  value?: string;
  suffix?: string;
  label?: string;
  component: "statCard";
  _uid: string;
  [k: string]: unknown;
}

export interface StatsSection {
  headline?: Headline[];
  description?: string;
  stat_card?: StatCard[];
  background_color?: "" | "Default" | "Primary" | "Muted" | "Secondary";
  component: "statsSection";
  _uid: string;
  [k: string]: unknown;
}

export interface TeamCard {
  image?: StoryblokAsset;
  name?: string;
  role?: string;
  component: "teamCard";
  _uid: string;
  [k: string]: unknown;
}

export interface TestimonialCard {
  feedback?: string;
  image?: StoryblokAsset;
  name?: string;
  role?: string;
  component: "testimonialCard";
  _uid: string;
  [k: string]: unknown;
}

export interface TestimonialSection {
  headline?: Headline[];
  description?: string;
  testimonial_card?: TestimonialCard[];
  component: "testimonialSection";
  _uid: string;
  [k: string]: unknown;
}

export interface WhyChooseUs {
  headline?: (
    | AboutSummary
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OtherHeroSection
    | OurSevices
    | OurTeam
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesPart
    | ServicesSection
    | SiteLogo
    | Socails
    | SocialLinks
    | StatCard
    | StatsSection
    | TeamCard
    | TestimonialCard
    | TestimonialSection
    | WhyChooseUs
    | WorkProcess
    | WorkProcessCard
  )[];
  description?: string;
  entries?: Entries[];
  component: "whyChooseUs";
  _uid: string;
  [k: string]: unknown;
}

export interface WorkProcess {
  header?: Headline[];
  description?: string;
  workProcessCard?: WorkProcessCard[];
  columns?: "" | "2" | "3" | "4";
  background_color?: "" | "Primary" | "Muted" | "Secondary" | "Default";
  component: "workProcess";
  _uid: string;
  [k: string]: unknown;
}

export interface WorkProcessCard {
  icon?: StoryblokAsset;
  title?: string;
  description?: string;
  icon_width?: "" | "48" | "80" | "160" | "200";
  row_span?: "" | "1" | "2";
  border?: boolean;
  card_bg_color?: "" | "Primary" | "Secondary" | "Muted" | "Default";
  component: "workProcessCard";
  _uid: string;
  [k: string]: unknown;
}
