// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface AuthItem {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  style?: "" | "Default" | "Ghost";
  background_color?: "" | "Primary" | "Highligh_1" | "hHghlight_2";
  text_color?: "" | "White" | "Dark";
  small?: "" | "Small" | "Medium" | "Large";
  component: "authItem";
  _uid: string;
  [k: string]: unknown;
}

export interface Buttons {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "buttons";
  _uid: string;
  [k: string]: unknown;
}

export interface Entries {
  image?: StoryblokAsset;
  headline?: string;
  description?: StoryblokRichtext;
  button?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  component: "entries";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterAbout {
  description?: string;
  socials?: Socails[];
  component: "footerAbout";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterItem {
  title?: string;
  footer_item?: InnierFooterItem[];
  component: "footerItem";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterSection {
  footer_about?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  learn?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  category?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  legal_support?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  component: "footerSection";
  _uid: string;
  [k: string]: unknown;
}

export interface GridCard {
  label?: string;
  description?: string;
  grid_button?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  icon?: StoryblokAsset;
  icon_width?: "" | "48px" | "80px" | "160px" | "200px";
  row_span?: "" | "One" | "Two";
  border?: boolean;
  image?: StoryblokAsset;
  component: "gridCard";
  _uid: string;
  [k: string]: unknown;
}

export interface HappyCustomer {
  headline?: Headline[];
  description?: StoryblokRichtext;
  background_color?: "" | "White" | "Primary";
  reverser_mobile_layout?: boolean;
  reverse_destop_layout?: boolean;
  button?: Buttons[];
  image?: StoryblokAsset;
  image_aspect_ratio?: boolean;
  component: "happyCustomer";
  _uid: string;
  [k: string]: unknown;
}

export interface HeaderNav {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "headerNav";
  _uid: string;
  [k: string]: unknown;
}

export interface Headline {
  text?: string;
  highlight?: "" | "Default Highlight" | "Primary Highlight" | "Secondary Highlight";
  component: "headline";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  servicing?: string;
  headline?: Headline[];
  description?: string;
  buttons?: Buttons[];
  image?: StoryblokAsset;
  preserve_image_ratio?: boolean;
  works?: Headline[];
  component: "heroSection";
  _uid: string;
  [k: string]: unknown;
}

export interface InnierFooterItem {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "innierFooterItem";
  _uid: string;
  [k: string]: unknown;
}

export interface NavBar {
  logo_title?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  header_nav?: HeaderNav[];
  auth_item?: AuthItem[];
  component: "navBar";
  _uid: string;
  [k: string]: unknown;
}

export interface OurSevices {
  headline?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  description?: string;
  grid_card?: GridCard[];
  columns?: "" | "Two" | "Three" | "Four";
  background_color?: "" | "white" | "primary";
  general_button?: Buttons[];
  component: "ourSevices";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface ProviderDetails {
  image?: StoryblokAsset;
  name?: string;
  service?: string;
  email?: string;
  phone_number?: string;
  get_in_touch?: Buttons[];
  component: "providerDetails";
  _uid: string;
  [k: string]: unknown;
}

export interface ProviderSection {
  headline?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  description?: string;
  search_placeholder?: string;
  providers_headline?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  provider_details?: ProviderDetails[];
  component: "providerSection";
  _uid: string;
  [k: string]: unknown;
}

export interface ServiceDetails {
  title?: string;
  details?: string;
  image?: StoryblokAsset;
  image_aspect_ratio?: boolean;
  component: "serviceDetails";
  _uid: string;
  [k: string]: unknown;
}

export interface ServicesHeroSection {
  headline?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  description?: string;
  image?: StoryblokAsset;
  component: "ServicesHeroSection";
  _uid: string;
  [k: string]: unknown;
}

export interface ServicesSection {
  headline?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  description?: StoryblokRichtext;
  service_details?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  component: "servicesSection";
  _uid: string;
  [k: string]: unknown;
}

export interface SiteLogo {
  logo?: StoryblokAsset;
  site_name?: Headline[];
  component: "siteLogo";
  _uid: string;
  [k: string]: unknown;
}

export interface Socails {
  icon?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "socails";
  _uid: string;
  [k: string]: unknown;
}

export interface WhyChooseUs {
  headline?: (
    | AuthItem
    | Buttons
    | Entries
    | FooterAbout
    | FooterItem
    | FooterSection
    | GridCard
    | HappyCustomer
    | HeaderNav
    | Headline
    | HeroSection
    | InnierFooterItem
    | NavBar
    | OurSevices
    | Page
    | ProviderDetails
    | ProviderSection
    | ServiceDetails
    | ServicesHeroSection
    | ServicesSection
    | SiteLogo
    | Socails
    | WhyChooseUs
  )[];
  description?: string;
  entries?: Entries[];
  component: "whyChooseUs";
  _uid: string;
  [k: string]: unknown;
}
