// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface Buttons {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "buttons";
  _uid: string;
  [k: string]: unknown;
}

export interface Entries {
  image?: StoryblokAsset;
  headline?: string;
  description?: StoryblokRichtext;
  button?: (Buttons | Entries | Headline | HeroSection | Page | ProviderDetails | ProviderSection | WhyChooseUs)[];
  component: "entries";
  _uid: string;
  [k: string]: unknown;
}

export interface Headline {
  text?: string;
  highlight?: "" | "Default Highlight" | "Primary Highlight" | "Secondary Highlight";
  component: "headline";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  servicing?: string;
  headline?: Headline[];
  description?: string;
  buttons?: Buttons[];
  image?: StoryblokAsset;
  preserve_image_ratio?: boolean;
  works?: Headline[];
  component: "heroSection";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Buttons | Entries | Headline | HeroSection | Page | ProviderDetails | ProviderSection | WhyChooseUs)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface ProviderDetails {
  image?: StoryblokAsset;
  name?: string;
  service?: string;
  email?: string;
  phone_number?: string;
  get_in_touch?: (
    | Buttons
    | Entries
    | Headline
    | HeroSection
    | Page
    | ProviderDetails
    | ProviderSection
    | WhyChooseUs
  )[];
  component: "providerDetails";
  _uid: string;
  [k: string]: unknown;
}

export interface ProviderSection {
  headline?: (Buttons | Entries | Headline | HeroSection | Page | ProviderDetails | ProviderSection | WhyChooseUs)[];
  search_placeholder?: string;
  providers_headline?: (
    | Buttons
    | Entries
    | Headline
    | HeroSection
    | Page
    | ProviderDetails
    | ProviderSection
    | WhyChooseUs
  )[];
  provider_details?: ProviderDetails[];
  component: "providerSection";
  _uid: string;
  [k: string]: unknown;
}

export interface WhyChooseUs {
  headline?: (Buttons | Entries | Headline | HeroSection | Page | ProviderDetails | ProviderSection | WhyChooseUs)[];
  description?: string;
  entries?: Entries[];
  component: "whyChooseUs";
  _uid: string;
  [k: string]: unknown;
}
